apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    app: example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
        custom-label: my-custom-value
    spec:
      containers:
      - name: example-container
        image: nginx:latest
        volumeMounts:
        - name: labels-volume
          mountPath: /etc/pod-info
      volumes:
      - name: labels-volume
        downwardAPI:
          items:
          - path: custom-label.txt
            fieldRef:
              fieldPath: metadata.labels['custom-label']
