FROM python:3.11-alpine

WORKDIR /app

COPY requirements.txt requirements.txt
COPY app.py app.py

RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir config

ENV FLASK_APP=app.py

EXPOSE 8080

CMD ["python", "app.py"]
